### ISSUE TITLE
[Discuss] page.post is an Object!

### ISSUE THREAD

**Issue by momocow** [AlynxZhou/hexo-renderer-nunjucks#1]
Hi, I am here to share the experience developing Hexo plugins.

I have been digging very much into Hexo's source code since I think Hexo's document is **NOT friendly** enough for plugin development.

---

> Some of Hexo's varibles are not the same type as they looks like, for example, in index template, you may think page.posts is an Array, but it's an Object (read here), which you cannot iterate it with for in, **I don't know why Hexo designs it so strange (more strange, some data structure of Hexo is "Array of ???", WHAT IS ????)**. OK, if you need an Array, use toArray() method like page.posts.toArray(), which is mentioned by @tommy351 (author of Hexo) here.

I'll provide my answer to what `page.post` is.

First of all, all local variables for template rendering is in `hexo.locals`, whose keys are variable names.

From [here](https://github.com/hexojs/hexo/blob/master/lib/hexo/index.js#L125) you can read that `page.posts` is the result of `db.model('Post').find(query)`. Since Hexo uses [Warehouse](https://github.com/hexojs/warehouse) as local JSON database, we can check in the Warehouse's document and find out that the return value of [`Model.find()`](https://hexojs.github.io/warehouse/Model.html#find) is a [Query](https://hexojs.github.io/warehouse/Query.html) object, which is actually what `page.posts` is.

`page.posts` is an Query object with [`#toArray()` method](https://hexojs.github.io/warehouse/Query.html#toArray) to return an array of [Document](https://hexojs.github.io/warehouse/Document.html) objects.

Each Document object is a Post Document whose schema is defined [here](https://github.com/hexojs/hexo/blob/master/lib/models/post.js#L18), therefore you can access these keys on the Schema object to read the attributes of a post.

---

That all about `page.posts`, happy blogging! 🎉

**Comment by AlynxZhou** [comment]
我知道 warehouse，也知道结果是个对象，就是吐槽一下 Hexo 的文档写的是个什么玩意，文档根本没提到里面还有个数据库，也没告诉你怎么把这个对象转成可以遍历的数组。最愚蠢的是 Hexo 自己修改了 swig 的for 标签让他自动执行 `toArray()`，看起来就像这东西是个数组一样，然后完全没有告诉使用其它模板语言的人到底是怎么回事，以为是个数组，遍历却报错了，然后傻了。我搜了好久才在一个 issue 里面找到解决方法。所以后来我自己写了个博客生成器，不用 Hexo 了，我的生成器用的就直接是内存里的对象引用，没有用什么数据库。

**Comment by momocow** [comment]
對於 Hexo 文檔的吐槽心有戚戚, 我也是踩著坑來的, 後來都是直接看代碼, 也才因此逐漸掌握這套工具。
哎, 工具還很多, 能找到一套用慣的就好。

純路過, 打擾了~

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo/commit/6d75199c8a7c31556b6c08d66775ee2f875b8868

**Comment by AlynxZhou** [comment]
> [hexojs/hexo@6d75199](https://github.com/hexojs/hexo/commit/6d75199c8a7c31556b6c08d66775ee2f875b8868)

Yes, I see this when I am building my own theme.

**Comment by yqs112358** [comment]
强烈希望hexo改进一下文档，开发者不应该必须通过阅读源码或者深挖issue才能知道某些东西该怎么写，现在文档里面的信息实在太少
